### ISSUE TITLE
Missing module `data.sequence` & Scripts to generate BabyAI trajectories

### ISSUE THREAD

**Issue by nlpdope** [brown-palm/abstract-state-seqmodel#1]
Dear authors @tttyuntian @zilaiz ,

Thanks for your fantastic work!  I have been attempting to run the code to pretrain the Transformer following your instruction. However, I noticed that the [`data.sequence`](https://github.com/brown-palm/abstract-state-seqmodel/blob/master/abstract-state-seqmodel/train.py#L12C1-L13C1) module is missing from your repo. Could you upload it so that I can run your code properly? 

Could you also share the scripts to generate the BabyAI GoToLocal and MiniBossLevel trajectories? It would be very useful for us to conduct the same analysis on other BabyAI subsets. 

Thank you in advance!

**Comment by tttyuntian** [comment]
Great to hear from you! We forgot to release`data.sequence` module, and will do it soon (should be done within 5 days), stay tuned for this!

We may need some time to organize the code to generate those trajectories, since it is inherited from original BabyAI repo. If you don't mind, do you want to email us directly (you should be able to get that from the paper) so that it may be easier for us to share the codebase to you.

**Comment by nlpdope** [comment]
Hi @tttyuntian ,

Thanks a lot for your timely response! I've just shot you an email.
